name: Build & Publish Application

on:
  push:
    branches:
      - "production"

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          corepack enable
          pnpm -v

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: pnpm i -r

      - name: Build and publish with Tauri
        uses: tauri-apps/tauri-action@v0
        id: build_and_publish
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          releaseName: "FindID v__VERSION__ â­"
          tagName: "latest"
          releaseDraft: true
          prerelease: false

      - name: Generate JSON file for updater
        run: |
          echo "${{ steps.build_and_publish.outputs.releaseId }}, ${{ steps.build_and_publish.outputs.releaseHtmlUrl }}, ${{ steps.build_and_publish.outputs.releaseUploadUrl }}, ${{ steps.build_and_publish.outputs.artifactPaths }}, ${{ steps.build_and_publish.outputs.appVersion }}" >> test.txt
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          git add test.txt
          git commit -m "Add test file"
          git push
