name: Build/Publish App & Release

on:
  push:
    branches:
      - "production"

jobs:
  build-and-publish:
    runs-on: windows-latest
    outputs:
      releaseId: ${{ steps.tauri.outputs.releaseId }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: pnpm i

      - name: Build/Publish to GitHub
        uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          releaseName: "v__VERSION__ ‚≠ê"
          tagName: "v__VERSION__"

  release-updater:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          RELEASE_ID: ${{ needs.build-and-publish.outputs.releaseId }}
        run: sh .github/scripts/latest.sh

      - name: Upload latest release
        uses: EndBug/add-and-commit@v9
        with:
          add: "latest.json"
          message: "Update latest.json"
